---
title: "Forecasting Baseline"
output: html_document
date: "2023-03-04"
---
Setting path
NOTE: In order to run the script smoothly we recommend to have saved the folder
containing all the data sets in a separate folder called "Data-OW"

```{r Path Setting}
path = "../Data-OW/"
```

Importing libraries
```{r Importing Libraries and parameters setting}
pacman::p_load(readxl,lubridate,dplyr,timechange,stringr, 
               ggplot2, ggrepel, tidyverse, ggcharts, car, forecast)

# Removing scientific notation

options(scipen=999)
```

```{r Loading the necessary data}

load(paste0(path, "MergedData.RData"))
cpi.df <- read_xlsx(paste0(path, "Consumer Price Index_vShared.xlsx"))
holiday.df <- read.table(paste0(path,"Hackathon_HolidaysMY_vShared.csv"), 
                                       header = TRUE,
                                       sep = ",")

```

```{r Brief Data sets preparation}

cpi.df$Date_daily <- as.character(cpi.df$Date_daily)
cpi.df$Date_daily <- as.POSIXct(cpi.df$Date_daily, 
                                format = "%Y-%m-%d",
                                tz = time_at_tz(Sys.timezone(location = TRUE)))

cpi.df<- cpi.df[between(cpi.df$Date_daily, as.POSIXct("2020-01-01"), as.POSIXct("2022-12-31")),]
```

```{r Creating Prediction Dataset}
sales <- transaction.df %>% 
  select(ProductKey, TransactionDate, WeekendFlag, UnitVolume, ActualSales, SalesDiscount,
         RetailFullPrice, DistributionChannel) %>% 
  filter(DistributionChannel == "Physical")    %>% 
  filter(ProductKey %in% c("49340","49341","49333","49329")) %>% 
  group_by(TransactionDate, ProductKey, WeekendFlag) %>% 
  summarise(SumDiscounts = sum(SalesDiscount),
            SumFullPrices = sum(RetailFullPrice),
            TotVolumes = sum(UnitVolume)) %>% 
  ungroup() %>% 
  mutate(PromoFlag = case_when((abs(SumDiscounts)/SumFullPrices) > 0.05 ~ 1,
                               TRUE ~ 0),
         Date = as.POSIXct(TransactionDate, format = "%Y-%m-%d",  
                           tz = time_at_tz(Sys.timezone(location = TRUE))),
         AvgPrice = (SumFullPrices-SumDiscounts)/TotVolumes)

# Checking 
table(sales$PromoFlag)

```
```{r Adding Exogenous factors}

# CPI
colnames(cpi.df)[3] <- "Date"
df <- left_join(sales[,-c(1)], cpi.df[,c(3,4)], by = "Date")

# Holidays
# Data Frame Creation on the basis of holidays.df

holidays <- stack(as.data.frame(cbind(rep("Chinese New Years Day",4),
                                rep("Federal Territory Day",4),
                                rep("Hari Raya Puasa (End of Ramadan)",4),
                                rep("Labor Day",4),
                                rep("Wesak Day (Buddhas Birthday), Kings Birthday",4),
                                rep("Hari Raya Qurban (Feast of Sacrifice)",4),
                                rep("Awal Muharram (Islamic New Year)",4),
                                rep("Merdeka Day (National Day)",4),
                                rep("Milad un Nabi (Birth of the Prophet Muhammad)",4),
                                rep("Deepavali (Festival of Lights)",4),
                                rep("Christmas Day",4))))

Date <- stack(as.data.frame(cbind(c("2020-01-22", "2021-01-22", "2022-01-22", "2023-01-22"),
                                  c("2020-02-01", "2021-02-01", "2022-02-01", "2023-02-01"),
                                  c("2020-05-24", "2021-05-13", "2022-05-02", "2023-04-22"),
                                  c("2020-05-01", "2021-05-01", "2022-05-01", "2023-05-01"),
                                  c("2020-05-26", "2021-05-26", "2022-05-26", "2023-05-26"),
                                  c("2020-06-31", "2021-07-20", "2022-07-10", "2023-06-29"),
                                  c("2020-08-20", "2021-08-09", "2022-06-30", "2023-07-19"),
                                  c("2020-08-31", "2021-08-31", "2022-08-31", "2023-08-31"),
                                  c("2020-10-28", "2021-10-18", "2022-10-07", "2023-09-26"),
                                  c("2020-11-14", "2021-11-04", "2022-10-24", "2023-10-12"),
                                  c("2020-12-25", "2021-12-25", "2022-12-25", "2023-12-25"))))

holidays.df <- cbind(holidays, Date)[,-c(2,4)]
colnames(holidays.df) <- c("Festivity", "Date")

holidays.df$Date<- as.POSIXct(holidays.df$Date, format = "%Y-%m-%d",  
                              tz = time_at_tz(Sys.timezone(location = TRUE)))

final_df <- left_join(df, holidays.df, by = "Date")
final_df <- final_df %>% 
  mutate(Festivity = case_when(is.na(Festivity) ~ 0,
                   TRUE ~ 1))

# Checking
table(final_df$Festivity)
```
```{r Completed Data set for Baseline Predction}
summary(final_df)
```

