---
title: "Dashboard"
output: html_notebook
---
Setting path
NOTE: In order to run the script smoothly we recommend to have saved the folder
containing all the data sets in a separate folder called "Data-OW"

```{r Path Setting}
path = "../Data-OW/"
```

Importing libraries
```{r Importing Libraries and parameters setting}
pacman::p_load(lubridate,dplyr,timechange,stringr,shinydashboard, 
               shiny, ggplot2, shinythemes, ggrepel, shinyWidgets,
               ggcharts, packcircles, viridis, ggiraph, gcookbook)

# Removing scientific notation

options(scipen=999)

```

```{r Loading the Pre-Processed Data}
load(paste0(path,"DBData.RData"))
```

```{r Preparation, aka Factorization}

cols <- c("DistributionChannel", "ProductCategory_Lvl2", "StoreKey", "ProductKey", 
          "PromoMechanic", "Region_Lvl1", "Region_Lvl2", "StoreType", "FestivityFlag")

Sales[cols] <- lapply(Sales[cols], factor)
Sales <- subset(Sales, select = -c(Festivity))
```


```{r UI-Creation}

ui <- fluidPage(
  tags$head(
        tags$style(HTML("
            code {
                color: #00559F;
                display:block;
                padding:9.5px;
                margin:0 0 12px;
                margin-top:12px;
                font-size:15px;
                line-height:25px;
                word-break:break-all;
                word-wrap:break-word;
                white-space:pre-wrap;
                background-color:#F5F5F5;
                border:1px solid rgba(0,0,0,0.15);
                border-radius:6px; 
                font-family:monospace;} 
           "))),
  theme = shinytheme("flatly"),
  navbarPage( 
  title = "OW - Hackatow",
  tabPanel("Exploratory Analysis",
           sidebarPanel(
             tags$h3("Slicers"), # "h3" is the heading's size
             sliderInput(inputId = "Time", # Creating the slider on the side 
                         label = "Date",
                  min = as.POSIXct("2020-01-01", format = "%Y-%m-%d", tz = ""),
                  max = as.POSIXct("2022-12-31", format = "%Y-%m-%d", tz = ""),
                  value = c(min(Sales$TransactionDate), 
                            max(Sales$TransactionDate)),
                  timeFormat="%Y-%m-%d",
                  timezone = "+0100"),
             
              pickerInput(inputId = "ProductID",
                         label = "ProductKey",
                         choices = levels(Sales$ProductKey),
                         options = list('actions-box' = TRUE,
                                        'liveSearch' = TRUE,
                                        'showTick' = TRUE),
                         multiple = TRUE,
                         selected = c("49340", "49341", "49333","49329")),
             
             checkboxGroupInput(inputId = "Channel",
                         label = "Channel",
                         choices = c("Online", "Physical"),
                         selected = c("Online", "Physical")),
             
             pickerInput(inputId = "StoreID",
                         label = "StoreKey",
                         choices = levels(Sales$StoreKey),
                         options = list('actions-box' = TRUE,
                                        'liveSearch' = TRUE,
                                        'showTick' = TRUE),
                         multiple = TRUE,
                         selected = "2071"
                         ),
             
             checkboxGroupInput(inputId = "Category",
                         label = "Category",
                         choices = levels(Sales$ProductCategory_Lvl2),
                         selected = "AC", 
                         inline = TRUE),
             
             pickerInput(inputId = "Promo",
                         label = "PromoMechanic",
                         choices = levels(Sales$PromoMechanic),
                         options = list('actions-box' = TRUE,
                                        'liveSearch' = TRUE,
                                        'showTick' = TRUE),
                         multiple = TRUE,
                         selected = "Percentage off"),
             
             numericInput(inputId = "TopN",
                          label = "Top-N-Pareto",
                          value = 5, 
                          max = 20,
                          min = 3),
             
             downloadButton(outputId = "report", 
                            label = "Generate report")
             ),
           
           mainPanel(
            tabsetPanel(type = "tabs",
              tabPanel(#splitLayout(cellWidths = c("60%", "20%", "20%")),
                                tags$p("Aggregate Sales Volumes"),
                                plotOutput(outputId = "SalesVolumes"),
                                # tags$p("Summary Statistics"),
                                #valueBoxOutput(outputId = "MeanDiscount"),
                                #valueBoxOutput(outputId = "MeanSale"),
                                valueBoxOutput(outputId = "TotalSales1"),
                                valueBoxOutput(outputId = "TotalDiscount1"),
                                valueBoxOutput(outputId = "Volumes1"),
                                code("This graph serves to have a general overview of Sales and Disocunts behaviours")),
              
              tabPanel(tags$p("Volumes by PromoMechanic"),
                       code("Which are the Promtion mostly used?"),
                       plotOutput(outputId = "PromotionMechanism"),
                       valueBoxOutput(outputId = "TotalSales2"),
                       valueBoxOutput(outputId = "TotalDiscount2"),
                       valueBoxOutput(outputId = "Volumes2"),
                       code("KPIs for selected Values")
                       ),
              
              tabPanel(tags$p("Volumes by Stores"),
                       ggiraphOutput(outputId = "Store"),
                       valueBoxOutput(outputId = "TotalSales3"),
                       valueBoxOutput(outputId = "TotalDiscount3"),
                       valueBoxOutput(outputId = "Volumes3"),
                       code("Stores' Mapping by Sales")
                       ),
              
              tabPanel(tags$p("Category In-depth"),
                       plotOutput(outputId = "ParetoAnalysis"),
                       valueBoxOutput(outputId = "TotalSales5"),
                       valueBoxOutput(outputId = "TotalDiscount5"),
                       valueBoxOutput(outputId = "Volumes5"),
                       code("Which are the products that generate the most sales?")
                       ))
             )
           ),
  
  tabPanel("In-depth Analysis",
           sidebarPanel(tags$h3("Slicers"), # "h3" is the heading's size
             sliderInput(inputId = "Time2", # Creating the slider on the side 
                         label = "Date",
                  min = as.POSIXct("2020-01-01", format = "%Y-%m-%d", tz = ""),
                  max = as.POSIXct("2022-12-31", format = "%Y-%m-%d", tz = ""),
                  value = c(min(Sales$TransactionDate), 
                            max(Sales$TransactionDate)),
                  timeFormat="%Y-%m-%d",
                  timezone = "+0100"),
             
              pickerInput(inputId = "ProductID2",
                         label = "ProductKey",
                         choices = levels(Sales$ProductKey),
                         options = list('actions-box' = TRUE,
                                        'liveSearch' = TRUE,
                                        'showTick' = TRUE),
                         multiple = T,
                         selected = c("49340")),
             
             checkboxGroupInput(inputId = "Channel2",
                         label = "Channel",
                         choices = c("Online", "Physical"),
                         selected = c("Online", "Physical")),
             
             
             checkboxGroupInput(inputId = "Category2",
                         label = "Category",
                         choices = levels(Sales$ProductCategory_Lvl2),
                         selected = levels(Sales$ProductCategory_Lvl2), 
                         inline = TRUE),
             
             numericInput(inputId = "TopN2",
                          label = "Top-N-Pareto",
                          value = 5, 
                          max = 20,
                          min = 3),
             ),
           
           mainPanel(tabsetPanel(type = "tabs",
                                 tabPanel(tags$p("Products' Growth"),
                                          plotOutput(outputId = "CategoryGrowth"),
                                          valueBoxOutput(outputId = "TotalSales4"),
                                          valueBoxOutput(outputId = "TotalDiscount4"),
                                          valueBoxOutput(outputId = "Volumes4")
                                           ),
                                 
                                 tabPanel(tags$p("HolidaysEffect"),
                                          code("Are Sales during holidays statistically different?"),
                                          plotOutput(outputId = "HolidaysEffect"),
                                          valueBoxOutput(outputId = "Test"),
                                          code("The reported value explains whether the difference between the two means is significant or not")
                                          ),
                                 
                                 tabPanel(tags$p("CPIRelevance"),
                                          code("Attention: Select just one single ProductKey,otherwise the plot will not work!"),
                                          plotOutput(outputId = "CPI"),
                                          valueBoxOutput(outputId = "PV"),
                                          #br(),
            code("The reported value explains whether the coefficient related to CPI is significant or not in explaining Sales'trend")
                                          ),
            
                                  tabPanel(tags$p("PriceAnalysis"),
                                           plotOutput(outputId = "Price"),
                                           code("Pay Attention in avoiding to select too many products. The graph could become a mess"))
            
           )
          )
         )
        )
       )
    
```

```{r Server Creation}
server <- function(input, output){
  
  datasetInput <- reactive({
      Sales %>% 
      filter(TransactionDate >= input$Time[1] & TransactionDate <= input$Time[2]) %>% 
      filter(DistributionChannel %in% input$Channel) %>% 
      filter(StoreKey %in% input$StoreID) %>% 
      filter(ProductCategory_Lvl2 %in% input$Category) %>%
      filter(ProductKey %in% input$ProductID) %>% 
      group_by(Year = year(TransactionDate), Month = month(TransactionDate)) %>% 
      summarise(Daily_Mean = mean(ActualSales),
                Daily_Sum = sum(ActualSales),
                Daily_Discount = -sum(SalesDiscount),
                Volumes = sum(UnitVolume)) %>% 
      arrange(Month, Year) %>%
      mutate(Period = as.POSIXct(paste(Year, Month,"01", sep = "-"), format = "%Y-%m-%d"))
    })
  
  datasetInput2 <- reactive({
      Sales %>% 
      filter(TransactionDate >= input$Time[1] & TransactionDate <= input$Time[2]) %>% 
      filter(DistributionChannel %in% input$Channel) %>% 
      filter(StoreKey %in% input$StoreID) %>% 
      filter(ProductCategory_Lvl2 %in% input$Category) %>%
      filter(ProductKey %in% input$ProductID) %>% 
      group_by(TransactionDate, PromoMechanic, DistributionChannel) %>% 
      summarise(Daily_Mean = mean(ActualSales),
                Daily_Sum = sum(ActualSales),
                Daily_Discount = -sum(SalesDiscount),
                Volumes = sum(UnitVolume))
  })
  
  store.summary <- reactive({
      Sales %>% 
      select(StoreKey, StoreType, Region_Lvl1, Region_Lvl2, ActualSales, TransactionDate, 
             DistributionChannel, ProductCategory_Lvl2, ProductKey) %>% 
      filter(TransactionDate >= input$Time[1] & TransactionDate <= input$Time[2]) %>% 
      filter(DistributionChannel %in% input$Channel) %>% 
      filter(ProductCategory_Lvl2 %in% input$Category) %>%  
      filter(ProductKey %in% input$ProductID) %>% 
      group_by(StoreKey, StoreType, Region_Lvl1, Region_Lvl2) %>% 
      summarise(revenues = sum(ActualSales)) %>% 
      mutate(txt = paste("Store: ",StoreKey, "\n",
                         "Yearly sales: ", round(revenues/1000, digits = 0),"k$", "\n",
                         "Region lvl.1: ", Region_Lvl1, "\n",
                         "Region lvl.2: ", Region_Lvl2)) %>% 
      arrange(desc(revenues)) %>% 
      ungroup()
  })
  
  transactions.sag <- reactive({
    Sales %>% 
    filter(TransactionDate >= input$Time2[1] & TransactionDate <= input$Time2[2]) %>% 
    filter(DistributionChannel %in% input$Channel2) %>% 
    filter(ProductCategory_Lvl2 %in% input$Category2) %>%
    group_by(ProductCategory_Lvl2) %>%  
    arrange(TransactionDate) %>% 
    mutate(cum_rev = cumsum(ActualSales))
  })
  
  pareto.analysis <- reactive({
    Sales %>% 
    select(ProductKey, ProductCategory_Lvl2, 
           ActualSales, TransactionDate, DistributionChannel, StoreKey) %>% 
    filter(TransactionDate >= input$Time[1] & TransactionDate <= input$Time[2]) %>% 
    filter(DistributionChannel %in% input$Channel) %>% 
    filter(StoreKey %in% input$StoreID) %>% 
    filter(ProductCategory_Lvl2 %in% input$Category) %>% 
    group_by(ProductKey, ProductCategory_Lvl2) %>% 
    summarise(tot.revenues = sum(ActualSales)) %>% 
    na.omit() %>% 
    ungroup() %>% 
    arrange(desc(tot.revenues)) %>% 
    mutate(per.revenues = base::cumsum(tot.revenues)/sum(tot.revenues)) 
  })
  
  topN.products <- reactive({
    pareto.analysis() %>% 
      filter(ProductKey %in% pareto.analysis()$ProductKey[1:input$TopN])
  })
  
  Distributions <- reactive({
    Sales %>% 
      filter(TransactionDate >= input$Time2[1] & TransactionDate <= input$Time2[2]) %>% 
      filter(DistributionChannel %in% input$Channel2) %>% 
      filter(ProductCategory_Lvl2 %in% input$Category2) %>% 
      filter(ProductKey %in% input$ProductID2) %>% 
      group_by(TransactionDate, FestivityFlag) %>% 
      summarise(Sales = sum(ActualSales)) 
  })
  
  Inflation <- reactive({
    Sales %>% 
      filter(ProductKey %in% input$ProductID2) %>% 
      group_by(M = month(TransactionDate), Y = year(TransactionDate), CPI_Monthly) %>% 
      summarise(Sales = sum(ActualSales)) %>% 
      arrange(M) %>% 
      arrange(Y) %>% 
      mutate(Period = paste(Y, M, sep = "-"))
  })
    
    Trend <- reactive({
      data.frame(trend = as.numeric(stl(ts(Inflation()$Sales, 
                                    start = c(2020,1), 
                                    end = c(2022, 12), 
                                    frequency = 12), 
                                 s.window = "periodic")$time.series[,2]),
                    CPI_M = as.numeric(Inflation()$CPI_Monthly), 
                    Period = as.factor(Inflation()$Period))
    })
 
    Price <-  reactive({
      Sales %>% 
      select(TransactionDate, ProductCategory_Lvl2, 
             ProductKey, RetailFullPrice, UnitVolume, CPI_Monthly) %>%
      filter(TransactionDate >= input$Time2[1] & TransactionDate <= input$Time2[2]) %>%
      group_by(Year = year(TransactionDate), Month = month(TransactionDate),
               ProductCategory_Lvl2, ProductKey) %>% 
      summarise(price = sum(RetailFullPrice)/sum(UnitVolume), 
                CPI_Monthly = unique(CPI_Monthly)) %>% 
        ungroup() %>% 
        group_by(Year, Month, ProductCategory_Lvl2) %>% 
        mutate(category.price = mean(price)) %>% 
        arrange(Month) %>% 
        arrange(Year) %>% 
        filter(ProductKey %in% input$ProductID2) %>% 
        mutate(Period = paste(Year, Month, sep ="-"))
    
    })
    
  # BarPlot
  output$PromotionMechanism <- renderPlot({
    print(myplot2 <- ggplot(datasetInput2(), aes(x=DistributionChannel, 
                                                 y=Daily_Sum, fill=PromoMechanic)) +
    geom_bar(stat="identity", position=position_dodge()) +
   # geom_errorbar(aes(ymin=Daily_Sum, ymax=Daily_Sum), width=.2,
    #              position=position_dodge(.9)) + 
      scale_fill_brewer(palette="Paired") +        
      scale_x_discrete(guide = guide_axis(check.overlap = TRUE)) + 
      theme(panel.grid.major = element_blank(),
          # axis.line = element_line(colour = "black"),
            axis.title.x = element_blank(),
            axis.title.y = element_blank(),
            panel.background = element_rect(fill= NA),
            plot.background = element_rect(fill= NA)))
  })
  
  # Time Series
  output$SalesVolumes <- renderPlot({
    print(myplot <- ggplot(datasetInput(), aes(x = Period, group = 1)) +
                             geom_line(aes(y = Daily_Sum, colour = "Sales")) +
                             geom_line(aes(y = Daily_Discount*(max(Daily_Sum)/max(Daily_Discount)), colour = "Discounts")) +
                             scale_colour_manual("",
                      breaks = c("Sales", "Discounts"),
                      values = c("#00559F", "green4")) +
            scale_y_continuous(
            # Features of the first axis
            name = "AggregateSales",
            # Add a second axis and specify its features
            sec.axis = sec_axis(~.*max(datasetInput()$Daily_Sum)/max(datasetInput()$Daily_Discount), 
            name="AggregateDiscount")) +
            theme(# panel.grid.major = element_blank(),
                  # axis.line = element_line(colour = "black"),
                  axis.title.x = element_blank(),
                  axis.title.y = element_blank(),
                  panel.background = element_rect(fill=NA),
                  plot.background = element_rect(fill=NA)))
  })
  
  #output$MeanDiscount <- renderValueBox({
   # valueBox(subtitle = mean(datasetInput()$Daily_Discount),
    #         value = "MeanDailyDiscount (MYR)")
 # })
  
  #output$MeanSale <- renderValueBox({
   # valueBox(subtitle = mean(datasetInput()$Daily_Sum),
    #         value = "MeanDailySales (MYR)")
  #})
  
  lapply(1:5, function(nr){
    output[[paste0("Volumes", nr)]] <- renderValueBox({
    valueBox(
    subtitle = sum(datasetInput()$Volumes),
    value = "Volumes (Unit)",
    width = 4,
    color = "navy")
      })      
  })
  
  lapply(1:5, function(nr){
    output[[paste0("TotalDiscount", nr)]] <- renderValueBox({
    valueBox(
    subtitle = sum(datasetInput()$Daily_Discount),
    value = "TotDiscount ($)",
    width = 4,
    color = "navy")})      
  })
   
   lapply(1:5, function(nr){
    output[[paste0("TotalSales", nr)]] <- renderValueBox({
    valueBox(
    subtitle = sum(datasetInput()$Daily_Sum),
    value = "TotSales ($)",
    width = 4,
    color = "navy")})      
  })

  output$Store <- ggiraph::renderggiraph({
    packing <- circleProgressiveLayout(store.summary()$revenues, sizetype = "area")
    data <- cbind(store.summary(), packing)
    data.gg <- circleLayoutVertices(packing, npoints = 50)

    p <- ggplot() +
    geom_polygon_interactive(data = data.gg,
                             aes(x = x, y = y, group = id, fill = id,
                                 tooltip = data$txt[id], data_id = id),
                             colour = "black", alpha = 0.6) +
    scale_fill_viridis() +
    geom_text(data = data,
              aes(x = x, y = y, label = StoreKey),
              size = 2, colour = "black") +
    theme_void() + 
    theme(legend.position = "none") +
    coord_equal()
  
  # Interactive
  widg <- ggiraph::ggiraph(ggobj = p, width_svg = 7, height_svg = 7)
  widg
  })

  output$CategoryGrowth <- renderPlot({
    ggplot(transactions.sag(), aes(x = TransactionDate, y = cum_rev,
                                    fill = ProductCategory_Lvl2)) + 
      labs(fill = "Product Category\nLvl. 2", 
           x = "Transaction Date",y = "Cumulative revenues" ) +
      geom_area(color = "black", linewidth = 0.2, alpha = 0.6) +
       theme(# panel.grid.major = element_blank(),
                  # axis.line = element_line(colour = "black"),
                  axis.title.x = element_blank(),
                  axis.title.y = element_blank(),
                  panel.background = element_rect(fill=NA),
                  plot.background = element_rect(fill=NA))
  })
  
  output$ParetoAnalysis <- renderPlot({
    print(ggplot(data = topN.products(), aes(x = factor(ProductKey, levels = ProductKey), y = per.revenues)) +
    geom_bar(stat = "identity", aes(fill = topN.products()$tot.revenues, alpha = 0.6)) +
    geom_hline(yintercept = 0.75, colour = "#00559F") +
    geom_hline(yintercept = 0.90, colour = "green4") +
    geom_point() +
    geom_path() +
    scale_x_discrete(breaks = topN.products()$ProductKey) +
    ylab("Cumulated revenues") +
    xlab("ProductKey") + 
    theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1),
          panel.background = element_rect(fill=NA),
          plot.background = element_rect(fill=NA),
          legend.position =  'none',
          axis.title.x = element_blank(),
          axis.title.y = element_blank()))
  })
  
  output$HolidaysEffect <- renderPlot({
      ggplot(Distributions(), aes(x=Sales, fill=FestivityFlag)) +
      geom_density(alpha=0.4) + 
      geom_vline(data=plyr::ddply(Distributions(), "FestivityFlag", 
                                  summarise, grp.mean=mean(Sales)), 
             aes(xintercept=grp.mean, color=FestivityFlag),
             linetype="dashed") +
      theme(panel.background = element_rect(fill=NA),
            plot.background = element_rect(fill=NA),
            axis.title.x = element_blank(),
            axis.title.y = element_blank())
  })
  
  output$Test <- renderValueBox({
    valueBox(value = "P-Value ",
             subtitle = t.test(Sales ~ FestivityFlag, data = Distributions())$p.value)
  })
  
  output$CPI <- renderPlot({
  ggplot(Trend(), aes(x = Period, group = 1)) +
            geom_line(aes(y = scale(trend), colour = as.character(input$ProductID2))) + 
            geom_line(aes(y = scale(CPI_M), colour = "CPI")) + 
  scale_colour_manual("",
                      breaks = c(as.character(input$ProductID2), "CPI"),
                      values = c("#00559F", "green4")) +
            theme(# panel.grid.major = element_blank(),
                  # axis.line = element_line(colour = "black"),
                  axis.title.x = element_blank(),
                  axis.title.y = element_blank(),
                  panel.background = element_rect(fill=NA),
                  plot.background = element_rect(fill=NA),
                  axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=0.5))
  })
  
  output$PV <- renderValueBox({
    valueBox("P-Value", coefficients(summary(lm(trend ~ CPI_M, data = Trend())))[2,4],
    color = "purple")
  })
  
  output$Price <- renderPlot({
    ggplot(data = Price(), aes(x = factor(Period, levels = unique(Period)), 
                               y = price, group = ProductKey)) +
      geom_line(aes(color = ProductKey)) +
      geom_line(data = Price(), aes(y = CPI_Monthly), colour = "red") + 
      geom_line(data = Price(), aes(y = category.price, 
                                    group = ProductCategory_Lvl2, 
                                    colour = ProductCategory_Lvl2)) +
      ylab("Price") + 
      xlab("Period") +
      theme(axis.title.x = element_blank(),
            axis.title.y = element_blank(),
            panel.background = element_rect(fill=NA),
            plot.background = element_rect(fill=NA),
            axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=0.5))
  })
  
}

```

```{r Dasboard at Glance}

shinyApp(ui, server)

```

