---
title: "Summary statistics"
output: html_notebook
---

```{r}
pacman::p_load(ggplot2, tidyverse, lubridate, packcircles, viridis, ggiraph,
               lattice, gcookbook, tidyr, timechange, readr)

```

```{r Importing data}
path = "../Data-OW/"
load(file = paste0(path,"MergedData.RData"))
df <- transaction.df
remove(transaction.df)
```

```{r Specify the timeframe of analysis}
start.date <- "2020-01-01"
end.date <- "2022-12-31"
```

```{r Total sum of all sales, volume and discount}
sales.volumes.discounts.tot <- df %>% 
  select(TransactionDate, UnitVolume, ActualSales, SalesDiscount, StoreKey, ProductKey, ProductCategory_Lvl2,
         DistributionChannel) %>% 
  filter(TransactionDate %within% interval(start = as.POSIXct(start.date,
                                                          format = "%Y-%m-%d",
                                                          tz = time_at_tz(Sys.timezone(location = TRUE))),
                                       end = as.POSIXct(end.date,
                                                        format = "%Y-%m-%d",
                                                        tz = time_at_tz(Sys.timezone(location = TRUE))))) %>% 
  group_by(Year = year(TransactionDate)) %>% 
  arrange(Year) %>% 
  summarise(yearly.volumes = sum(UnitVolume),
            yearly.sales = sum(ActualSales),
            yearly.discounts = sum(SalesDiscount))

```

```{r Sum of discounts by PromoMechanic}
promo.to.exclude <- ""

disc.bypromo <- df %>% 
  select(TransactionDate, UnitVolume, ActualSales, SalesDiscount, StoreKey, ProductKey, ProductCategory_Lvl2,
         DistributionChannel, PromoMechanic) %>% 
  filter(!(PromoMechanic %in% promo.to.exclude)) %>%
  group_by(Year = year(TransactionDate), PromoMechanic) %>% 
  arrange(Year) %>% 
  summarise(yearly.discounts = round(sum(SalesDiscount),digits = 0))
  
```


```{r Sales by Channel}
channel.filter <- c("Online", "Physical")

channel.sales <- df %>% 
  select(TransactionDate, UnitVolume, ActualSales, SalesDiscount, StoreKey, ProductKey, ProductCategory_Lvl2,
         DistributionChannel, PromoMechanic) %>% 
  filter(DistributionChannel %in% channel.filter) %>%
  group_by(Year = year(TransactionDate), DistributionChannel) %>% 
  arrange(Year) %>% 
  summarise(yearly.volumes = round(sum(UnitVolume),digits = 0),
            yearly.sales = round(sum(ActualSales),digits = 0),
            yearly.discounts = round(sum(SalesDiscount),digits = 0))
```

```{r Sales store}
store.filter <- "2071"

store.sales <- df %>% 
  select(TransactionDate, UnitVolume, ActualSales, SalesDiscount, StoreKey, ProductKey, ProductCategory_Lvl2,
         DistributionChannel, PromoMechanic) %>% 
  filter(StoreKey %in% store.filter) %>%
  group_by(Year = year(TransactionDate), StoreKey) %>% 
  arrange(Year) %>% 
  summarise(yearly.volumes = round(sum(UnitVolume),digits = 0),
            yearly.sales = round(sum(ActualSales),digits = 0),
            yearly.discounts = round(sum(SalesDiscount),digits = 0))

```

```{r Sales Category}
category.filter <- "AC"

category.sales <- df %>% 
  select(TransactionDate, UnitVolume, ActualSales, SalesDiscount, StoreKey, ProductKey, ProductCategory_Lvl2,
         DistributionChannel, PromoMechanic) %>% 
  filter(ProductCategory_Lvl2 %in% category.filter) %>%
  group_by(Year = year(TransactionDate), ProductCategory_Lvl2) %>% 
  arrange(Year) %>% 
  summarise(yearly.volumes = round(sum(UnitVolume),digits = 0),
            yearly.sales = round(sum(ActualSales),digits = 0),
            yearly.discounts = round(sum(SalesDiscount),digits = 0))

```


```{r Sales Product}
product.filter <- "49489"

product.sales <- df %>% 
  select(TransactionDate, UnitVolume, ActualSales, SalesDiscount, StoreKey, ProductKey, ProductCategory_Lvl2,
         DistributionChannel, PromoMechanic) %>% 
  filter(ProductKey %in% product.filter) %>%
  group_by(Year = year(TransactionDate), ProductKey) %>% 
  arrange(Year) %>% 
  summarise(yearly.volumes = round(sum(UnitVolume),digits = 0),
            yearly.sales = round(sum(ActualSales),digits = 0),
            yearly.discounts = round(sum(SalesDiscount),digits = 0))

```

